### ISSUE TITLE
importError: cannot import name 'multiGATEncoder' from 'models'

### ISSUE THREAD

**Issue by Sandhy30** [kybinn/Subtype-MGTP#2]
Hello,

I'm trying to run a script that imports multiGATEncoder from the models module, but I'm encountering the following error:

bash
Copy code
ImportError: cannot import name 'multiGATEncoder' from 'models'
I see that the code is referencing multiGATEncoder from models.py, but I couldn’t find the implementation in the repository. Could you please clarify if the multiGATEncoder is missing or if it has been renamed or moved? If it’s deprecated, is there an alternative I should be using?

Thank you in advance for your assistance!

**Comment by kybinn** [comment]
The multiGATEncoder is redundant, I forgot to delete it. I updated A_main.py
